In [27]:
import numpy as np
import math
import warnings

A = np.array([[1, -1, 0, 0],
            [-3, -3, -1, -1],
            [-1, -1, -3, 2],
             [-1, -2, 2, 1]])
'''
A = np.array([[1, -4, 1],
            [1, -2, 4],
            [0, 2, 3]])
 '''           
det = np.linalg.det(A)
print('Determinate:' + '\n' +str(round(det, 2))+ '\n')

trans = np.transpose(A)
print('A^T:' + '\n' + str(trans) + '\n')

if det != 0:
    warnings.simplefilter('ignore')
    A_inv = np.linalg.inv(A)
    print('A^-1:' +'\n' + str(np.around(A_inv, 2)) + '\n')
else:
    
    print('A is not invertible')
I = abs(A @ A_inv)
print(np.around(I, 2))

Determinate:
59.0

A^T:
[[ 1 -3 -1 -1]
 [-1 -3 -1 -2]
 [ 0 -1 -3  2]
 [ 0 -1  2  1]]

A^-1:
[[ 0.54 -0.12 -0.02 -0.08]
 [-0.46 -0.12 -0.02 -0.08]
 [-0.12 -0.07 -0.15  0.24]
 [-0.14 -0.22  0.25  0.27]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
theta = 0
B = np.array([[-1],
            [1],
             [0],
             [0]])

AB = A_inv @ B
print( 'AB:' + '\n' + str(AB))

AB:
[[ 0.        ]
 [ 0.        ]
 [ 0.33333333]
 [-0.33333333]]
