In [37]:
import numpy as np
import math
import warnings

A = np.array([[1, 3, 0],
            [1, 2, 3],
             [0, -1, 3]])
det = np.linalg.det(A)
print('Determinate:' + '\n' +str(det)+ '\n')

trans = np.transpose(A)
print('A^T:' + '\n' + str(trans) + '\n')

if det != 0:
    warnings.simplefilter('ignore')
    inv = np.linalg.inv(A)
    print('A^-1:' +'\n' + str(inv) + '\n')
else:
    print('A is not invertible')

Determinate:
0.0

A^T:
[[ 1  1  0]
 [ 3  2 -1]
 [ 0  3  3]]

A is not invertible


In [30]:
theta = 0
B = np.array([[math.cos(theta), -math.sin(theta)],
            [math.sin(theta), math.cos(theta)]])

AB = A @ B
print( 'AB:' + '\n\n' + str(AB))

AB:

[[3. 4.]
 [6. 5.]]
