In [52]:
####################################################################################################################
# import required packages
# Set A matrix
# b if needed to find the x matrix
#
## You will have to run the in order to get them to run
## Since variables and objects are defined in the prior cells
## HOwever, this does not apply to the Cramer's Rule cell 
####################################################################################################################

import numpy as np
import math
import warnings
from fractions import Fraction


A = np.array([[2, 3, 2],
            [-1, -3, -8],
            [-3, 2, -7]])

b = np.array([[-2],
            [-2],
             [2]])

In [53]:
####################################################################################################################
#Finding Transpose of A
####################################################################################################################
trans = np.transpose(A)
print('A^T:' + '\n' + str(trans) + '\n')

A^T:
[[ 2 -1 -3]
 [ 3 -3  2]
 [ 2 -8 -7]]



In [54]:
####################################################################################################################
# Finding Determinate of A
####################################################################################################################

det = np.linalg.det(A)
print('Determinate:' + '\n' +str(round(det, 2))+ '\n')


Determinate:
103.0



In [55]:
####################################################################################################################
# Finding the Inverse of A
####################################################################################################################

if det != 0:
    warnings.simplefilter('ignore')
    A_inv = np.linalg.inv(A)
    print('A^-1:' +'\n' + str(np.around(A_inv, 2)) + '\n')
else:
    
    print('A is not invertible')

A^-1:
[[ 0.36  0.24 -0.17]
 [ 0.17 -0.08  0.14]
 [-0.11 -0.13 -0.03]]



In [56]:
####################################################################################################################
# Finding the x matrix
####################################################################################################################

if det != 0:
    x = A_inv @ b
print('x:' + '\n' +str(x))


x:
[[-1.55339806]
 [ 0.09708738]
 [ 0.40776699]]


In [57]:
####################################################################################################################
# Using Cramer's Rule for a 3x3
####################################################################################################################

coeff = [[2, 3, 2, -2],
        [-1, -3, -8, -2],
        [-3, 2, -7, 2]]


d = [[coeff[0][0], coeff[0][1], coeff[0][2]],
    [coeff[1][0], coeff[1][1], coeff[1][2]],
    [coeff[2][0], coeff[2][1], coeff[2][2]]]

d1 = [[coeff[0][3], coeff[0][1], coeff[0][2]],
    [coeff[1][3], coeff[1][1], coeff[1][2]],
    [coeff[2][3], coeff[2][1], coeff[2][2]]]

d2 = [[coeff[0][0], coeff[0][3], coeff[0][2]],
    [coeff[1][0], coeff[1][3], coeff[1][2]],
    [coeff[2][0], coeff[2][3], coeff[2][2]]]

d3 = [[coeff[0][0], coeff[0][1], coeff[0][3]],
    [coeff[1][0], coeff[1][1], coeff[1][3]],
    [coeff[2][0], coeff[2][1], coeff[2][3]]]


D = np.linalg.det(d)
D1 = np.linalg.det(d1)
D2 = np.linalg.det(d2)
D3 = np.linalg.det(d3)

print("D is : ", str(round(D, 2)))
print("D1 is : ", str(round(D1, 2)))
print("D2 is : ", str(round(D2, 2)))
print("D3 is : ", str(round(D3, 2)))


if D != 0:

    x = D1 / D
    y = D2 / D

    z = D3 / D 

    print("Value of x is : ", x)
    print("Value of y is : ", y)
    print("Value of z is : ", z)

else:
    if (D1 == 0 and D2 == 0 and
        D3 == 0):
        print("Infinite solutions")
    elif (D1 != 0 or D2 != 0 or
        D3 != 0):
        print("No solutions")
        

D is :  103.0
D1 is :  -160.0
D2 is :  10.0
D3 is :  42.0
Value of x is :  -1.5533980582524265
Value of y is :  0.09708737864077667
Value of z is :  0.4077669902912621
